<script setup>
import StatusTag from '@/components/StatusTag.vue'
const props = defineProps({ diagnosis: { type: Object, default: null } })
const money = (value) => `¥${Number(value || 0).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const percent = (value) => value === null || value === undefined ? '—' : `${(Number(value) * 100).toFixed(1)}%`
const evidenceLabel = { current: '当前值', baseline: '基线值', change: '变化', current_ctr: '当前 CTR', baseline_ctr: '基线 CTR', current_cvr: '当前 CVR', baseline_cvr: '基线 CVR', stock: '库存', sales_qty: '销量', sellable_days: '可售天数', current_refund_rate: '当前退款率', baseline_refund_rate: '基线退款率', current_roi: '当前 ROI', baseline_roi: '基线 ROI' }
function evidenceValue(key, value) { if (value === null || value === undefined) return '—'; if (['change','current_ctr','baseline_ctr','current_cvr','baseline_cvr','current_refund_rate','baseline_refund_rate'].includes(key)) return percent(value); if (key === 'sellable_days') return `${Number(value).toFixed(1)} 天`; return Number.isFinite(Number(value)) ? Number(value).toLocaleString('zh-CN', { maximumFractionDigits: 2 }) : String(value) }
</script>
<template>
  <div v-if="!props.diagnosis" class="empty-state">尚未运行诊断</div>
  <div v-else class="diagnosis-panel">
    <article class="diagnosis-overview"><div class="diagnosis-score"><small>健康分</small><strong>{{ diagnosis.health_score }}</strong><StatusTag :value="diagnosis.severity"/></div><div><p class="section-kicker">OPERATING CONCLUSION</p><h3>{{ diagnosis.summary || '暂无诊断结论' }}</h3><div class="diagnosis-meta"><span>数据覆盖 {{ diagnosis.data_quality?.coverage_score || 0 }}%</span><span>基线 {{ diagnosis.data_quality?.baseline_days || diagnosis.baseline_days || 0 }} 天</span><span v-if="diagnosis.decomposition?.estimated_gmv_loss" class="loss-text">估算 GMV 缺口 {{ money(diagnosis.decomposition.estimated_gmv_loss) }}</span></div></div></article>
    <article class="card compact"><div class="card-heading"><div><p class="section-kicker">GMV DECOMPOSITION</p><h3>GMV 下降贡献拆解</h3></div></div><div v-if="diagnosis.decomposition?.factors?.length" class="decomposition-list"><div v-for="factor in diagnosis.decomposition.factors" :key="factor.key" class="decomposition-row"><span><strong>{{ factor.label }}</strong><small>{{ percent(factor.change) }}</small></span><strong>{{ factor.estimated_loss ? money(factor.estimated_loss) : '—' }}</strong></div></div><p v-else class="helper-text">数据不足时系统不会强行进行漏斗归因。</p></article>
    <section class="diagnosis-section"><div class="card-heading"><div><p class="section-kicker">PRIORITY QUEUE</p><h3>问题优先级</h3></div><span>{{ diagnosis.issues?.length || 0 }} 项</span></div><div v-if="diagnosis.issues?.length" class="diagnosis-issue-list"><article v-for="(issue, index) in diagnosis.issues" :key="issue.code" class="diagnosis-issue" :class="issue.severity"><header><div><p class="section-kicker">PRIORITY {{ index + 1 }}</p><h3>{{ issue.title }}</h3></div><div><StatusTag :value="issue.severity"/><strong class="priority-score">{{ issue.priority_score }}</strong></div></header><p>{{ issue.reason }}</p><div class="diagnosis-tags"><span>影响度 {{ issue.impact_score }}</span><span>置信度 {{ Math.round(Number(issue.confidence || 0) * 100) }}%</span><span v-if="issue.estimated_loss" class="loss-text">估算缺口 {{ money(issue.estimated_loss) }}</span></div><details v-if="Object.keys(issue.evidence || {}).length"><summary>查看触发依据</summary><div class="evidence-grid"><div v-for="(value, key) in issue.evidence" :key="key"><small>{{ evidenceLabel[key] || key }}</small><strong>{{ evidenceValue(key, value) }}</strong></div></div></details><div v-if="issue.actions?.length" class="action-plan"><strong>建议动作</strong><ol><li v-for="action in issue.actions" :key="action">{{ action }}</li></ol></div><div v-if="issue.validation_metrics?.length" class="validation-plan"><strong>验证指标</strong><span v-for="metric in issue.validation_metrics" :key="metric">{{ metric }}</span></div></article></div><div v-else class="empty-state">当前样本下未发现明显异常。</div></section>
    <article v-if="diagnosis.ai_analysis?.text" class="card"><p class="section-kicker">AI FOLLOW-UP</p><h3>AI 运营建议</h3><div class="ai-result">{{ diagnosis.ai_analysis.text }}</div></article>
  </div>
</template>
