<script setup>
import { onMounted, onBeforeUnmount, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getDashboard } from '@/api/workspace.js'
import { useAppStore } from '@/stores/app.js'
import SkuDrawer from '@/components/SkuDrawer.vue'
import StatusTag from '@/components/StatusTag.vue'
const app = useAppStore(); const router = useRouter(); const data = ref(null); const error = ref(''); const drawer = ref(null)
const money = (v) => `¥${Number(v || 0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const percent = (v) => v === null || v === undefined ? '—' : `${(Number(v)*100).toFixed(1)}%`
async function load(){ if(!app.selectedShopId){data.value=null;return} try{data.value=await getDashboard(app.selectedShopId);error.value=''}catch(e){error.value=e.message} }
function updated(){load()}
onMounted(()=>{load();window.addEventListener('pdd:data-updated',updated)}); onBeforeUnmount(()=>window.removeEventListener('pdd:data-updated',updated))
</script>
<template><section class="page-content"><article v-if="!app.selectedShopId" class="card empty-state"><strong>请先创建店铺</strong><button class="button primary" @click="router.push('/settings')">去设置</button></article><article v-else-if="error" class="card empty-state">{{error}}</article><template v-else-if="data"><article v-if="data.data_state==='empty'" class="card empty-state"><strong>当前店铺还没有经营数据</strong><p>连接拼多多同步，或导入经营报表。</p><button class="button primary" @click="router.push('/data')">去数据中心</button></article><template v-else><div class="stats-grid"><article class="stat-card"><span>当日 GMV</span><strong>{{money(data.metrics.gmv)}}</strong><small>{{data.latest_date}}</small></article><article class="stat-card"><span>销量</span><strong>{{data.metrics.sales_qty}}</strong><small>订单 {{data.metrics.order_count}}</small></article><article class="stat-card"><span>退款率</span><strong>{{percent(data.metrics.refund_rate)}}</strong></article><article class="stat-card"><span>商品 / SKU</span><strong>{{data.metrics.product_count}} / {{data.metrics.sku_count}}</strong></article></div><div class="dashboard-grid"><article class="card"><div class="card-heading"><div><p class="section-kicker">14 DAY TREND</p><h2>GMV 趋势</h2></div></div><div class="trend-bars"><div v-for="item in data.trend" :key="item.date" class="trend-bar"><span :style="{height:`${Math.max(6,(Number(item.gmv||0)/Math.max(...data.trend.map(x=>Number(x.gmv||0)),1))*160)}px`}"></span><small>{{item.date.slice(5)}}</small></div></div></article><article class="card"><div class="card-heading"><div><p class="section-kicker">PRIORITY</p><h2>优先处理 SKU</h2></div><button class="button ghost" @click="router.push('/skus')">查看全部</button></div><div class="issue-list"><button v-for="item in data.urgent_skus" :key="item.sku_id" class="issue-row" @click="drawer?.show(item.sku_id)"><span><strong>{{item.product_title}}</strong><small>{{item.sku_name}} · {{item.issue}}</small></span><span><StatusTag :value="item.severity"/><strong class="health-score">{{item.health_score}}</strong></span></button><div v-if="!data.urgent_skus?.length" class="empty-state">暂无待处理项</div></div></article></div></template></template><SkuDrawer ref="drawer"/></section></template>
